# Meta Data for SEO

## Homepage
title = "devPT"
titleSeparator = "-"
titleAddition = "Comunidade de Developers Portugueses"
description = "devPT é uma Comunidade de Developers Portugueses com o objetivo de facilitar a partilha de experiências, projetos e oportunidades de emprego."

## Open Graph + Twitter Cards
images = ["devpt.png"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "pt_PT"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-devpt.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/devpt-org"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Queres juntar-te à comunidade? <a class=\"alert-link\" href=\"https://discord.gg/52apEBYQb2\" target=\"_blank\">Entra no Discord</a>!"

# Alert
# alert = true
alertText = "Queres juntar-te à comunidade? <a class=\"alert-link\" href=\"https://discord.gg/52apEBYQb2\" target=\"_blank\">Entra no Discord</a>!"

# Edit Page
docsRepo = "https://github.com/devpt-org/devpt-org.github.io"
editPage = false
